package model;
// Generated 11-Nov-2023 11:12:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Studentinfo generated by hbm2java
 */
public class Studentinfo  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String rolenumber;
     private String gender;
     private String subject;
     private Date date;

    public Studentinfo() {
    }

    public Studentinfo(String name, String rolenumber, String gender, String subject, Date date) {
       this.name = name;
       this.rolenumber = rolenumber;
       this.gender = gender;
       this.subject = subject;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRolenumber() {
        return this.rolenumber;
    }
    
    public void setRolenumber(String rolenumber) {
        this.rolenumber = rolenumber;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


