 SELECT first_name, last_name, hire_date from employees 
 where department_id = (select department_id from employees
                        where first_name ='Clara')
                        AND first_name <> 'Clara';
                        
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%T%');
 
 SELECT EMPLOYEE_ID , FIRST_NAME, SALARY FROM EMPLOYEES
 WHERE SALARY >( SELECT AVG(SALARY) FROM EMPLOYEES)
AND DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE FIRST_NAME LIKE '%J%' );
 
 
 SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, JOB_ID FROM EMPLOYEES
 
 WHERE DEPARTMENT_ID =(SELECT DEPARTMENT_ID FROM DEPARTMENTS 
         WHERE LOCATION_ID =(SELECT LOCATION_ID FROM LOCATIONS
                        WHERE CITY = 'Toronto')); 
 
 
 
 
 SELECT E.FIRST_NAME, E.LAST_NAME, E.EMPLOYEE_ID, E.JOB_ID FROM EMPLOYEES E
 
 JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
    WHERE L.CITY='Toronto';  
 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID from EMPLOYEES
 WHERE SALARY < (SELECT MIN(SALARY) FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES
WHERE JOB_ID='MK_MAN'));
 

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID from EMPLOYEES

WHERE SALARY > ALL (SELECT AVG(SALARY) FROM EMPLOYEES
  GROUP BY DEPARTMENT_ID);
 
 
 SELECT DEPARTMENT_ID, SALARY AS TOTAL_SALARY FROM EMPLOYEES
 WHERE SALARY IN(SELECT SUM(SALARY) FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
 HAVING DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IS NOT NULL));
 
 SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES
  GROUP BY DEPARTMENT_ID
  HAVING (DEPARTMENT_ID IS NOT NULL);
  
  SELECT LAST_NAME, SALARY FROM EMPLOYEES
  WHERE MANAGER_ID =ALL (SELECT EMPLOYEE_ID FROM EMPLOYEES
  WHERE LAST_NAME ='KING');

SELECT LAST_NAME, DEPARTMENT_ID ,JOB_ID  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (
  SELECT DEPARTMENT_ID FROM DEPARTMENTS
  WHERE LOCATION_ID = 1700) ;
  
  SELECT * FROM EMPLOYEES WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES
  WHERE LAST_NAME='King');
 
 


