SELECT CONCAT(FIRST_NAME, CONCAT ('  ',LAST_NAME))"FULL NAME"
FROM EMPLOYEES;

SELECT SUBSTR  ('HELLOWORLD',-5)
FROM EMPLOYEES;

SELECT INSTR('HELLOWORLD', 'LL')
FROM DUAL;

SELECT FIRST_NAME, INSTR(FIRST_NAME, 'l')
FROM EMPLOYEES;

SELECT FIRST_NAME,SUBSTR(FIRST_NAME, 1, LENGTH (FIRST_NAME)-2)
FROM EMPLOYEES;

SELECT LPAD(FIRST_NAME,12,'$')
FROM EMPLOYEES;

SELECT * FROM JOBS
WHERE JOB_ID=UPPER('&JOB_TITLE');

SELECT CONCAT (CONCAT(LAST_NAME, '''s JOB CATEGORY IS  '), JOB_ID)
"JOB" FROM EMPLOYEES
WHERE SUBSTR (JOB_ID,4) = 'REP';

SELECT EMPLOYEE_ID, CONCAT(FIRST_NAME, LAST_NAME) NAME,
LENGTH (LAST_NAME), INSTR(LAST_NAME, 'a') "Contains 'a'?"
FROM EMPLOYEES
WHERE SUBSTR(LAST_NAME, -1, 1) = 'n';

SELECT LAST_NAME,
UPPER (CONCAT(SUBSTR(LAST_NAME, 1, 8), '_US'))
FROM EMPLOYEES
WHERE DEPARTMENT_ID= 60;

SELECT TRUNC(45.451, -1)
FROM DUAL;

SELECT LAST_NAME, HIRE_DATE 
FROM EMPLOYEES
WHERE HIRE_DATE < '01-FEB-2008';
