/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package from;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Employe extends javax.swing.JFrame {
     String sql="";
    PreparedStatement ps;
    ResultSet rs;
    Dbcoon con=new Dbcoon(); 
    
    
    public Employe() {
        initComponents();
        allEmployes();
    }

    public void allEmployes(){
    
    String[] columns={"ID","Name","Degnation","Salary"};
         DefaultTableModel modeli= new DefaultTableModel();
          modeli.setColumnIdentifiers(columns);
        tableEmploye.setModel(modeli);
         
         sql="select * from employes";
         
         try {
             ps=con.getconne().prepareStatement(sql);
             
             rs=ps.executeQuery();
             
             while(rs.next()){
             int id=rs.getInt("id");
             String name=rs.getString("name");
             String designa=rs.getString("designation");
             int salar=rs.getInt("salary");
             
             
             modeli.addRow(new Object[] {id,name,designa,salar});
             }
             
         } catch (SQLException ex) {
             Logger.getLogger(Employe.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    public void updatEmp(){
    
  sql="update employes set name=?,designation=?,salary=? where id=? ";
     
         try {
             ps=con.getconne().prepareStatement(sql);
             
             ps.setString(1,txtNaMee.getText().trim());
             ps.setString(2,txtdesignation.getText().trim());
             ps.setString(3, txtsalary.getText().trim());
            ps.setInt(4, Integer.parseInt(txtidid.getText().trim()));
             
             ps.executeUpdate();
             ps.close();
             
             JOptionPane.showMessageDialog(rootPane, "Data update");
             allEmployes();
         } catch (SQLException ex) {
             Logger.getLogger(Employe.class.getName()).log(Level.SEVERE, null, ex);
         }
    
    }
    
    public void reset(){
    txtidid.setText(null);
    txtNaMee.setText(null);
    txtdesignation.setText(null);
    txtsalary.setText(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtidid = new javax.swing.JTextField();
        txtNaMee = new javax.swing.JTextField();
        txtdesignation = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnupdat = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnresat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmploye = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employe Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 70));

        jLabel2.setText("Designation  :");

        jLabel3.setText("Emp-ID  :");

        jLabel4.setText("E--Name  :");

        jLabel5.setText("Salary");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 280));
        getContentPane().add(txtidid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, 40));
        getContentPane().add(txtNaMee, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 180, 40));
        getContentPane().add(txtdesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 180, 40));
        getContentPane().add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, 40));

        btnsave.setText("save");
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        btnupdat.setText("Update");
        btnupdat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdatMouseClicked(evt);
            }
        });
        getContentPane().add(btnupdat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        btndelete.setText("Delete");
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        btnresat.setText("Resat");
        btnresat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnresatMouseClicked(evt);
            }
        });
        getContentPane().add(btnresat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        tableEmploye.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEmploye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmployeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEmploye);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
        // TODO add your handling code here:
        sql="insert into employes(name,designation,salary)values(?,?,?)";
        
         try {
             ps=con.getconne().prepareStatement(sql);
             
             ps.setString(1,txtNaMee.getText().trim());
             ps.setString(2,txtdesignation.getText().trim());
             ps.setString(3,txtsalary.getText().trim());
             
             ps.executeUpdate();
             ps.close();
             con.getconne().close();
             JOptionPane.showMessageDialog(rootPane,"data is saved");
             allEmployes();
         } catch (SQLException ex) {
             Logger.getLogger(Employe.class.getName()).log(Level.SEVERE, null, ex);
                          JOptionPane.showMessageDialog(rootPane,"data is not save");

         }
    }//GEN-LAST:event_btnsaveMouseClicked

    private void btnupdatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdatMouseClicked
        // TODO add your handling code here:
        updatEmp();
    }//GEN-LAST:event_btnupdatMouseClicked

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        // TODO add your handling code here:
        sql="delete from employes where id=?";
        
         try {
             ps=con.getconne().prepareStatement(sql);
             ps.setInt(1, Integer.parseInt(txtidid.getText().trim()));
             ps.executeUpdate();
             ps.close();
             con.getconne().close();
             
             JOptionPane.showMessageDialog(rootPane, "Data delete");
              allEmployes();
         } catch (SQLException ex) {
             Logger.getLogger(Employe.class.getName()).log(Level.SEVERE, null, ex);
                          JOptionPane.showMessageDialog(rootPane, "Data is not delete");

         }
    }//GEN-LAST:event_btndeleteMouseClicked

    private void btnresatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresatMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnresatMouseClicked

    private void tableEmployeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmployeMouseClicked
        // TODO add your handling code here:
        int row=tableEmploye.getSelectedRow();
        
        String id=tableEmploye.getModel().getValueAt(row, 0).toString();
        String name=tableEmploye.getModel().getValueAt(row, 1).toString();
        String designation=tableEmploye.getModel().getValueAt(row, 2).toString();
        String salary=tableEmploye.getModel().getValueAt(row, 3).toString();
        
        txtidid.setText(id);
        txtNaMee.setText(name);
        txtdesignation.setText(designation);
        txtsalary.setText(salary);
        
    }//GEN-LAST:event_tableEmployeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnresat;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEmploye;
    private javax.swing.JTextField txtNaMee;
    private javax.swing.JTextField txtdesignation;
    private javax.swing.JTextField txtidid;
    private javax.swing.JTextField txtsalary;
    // End of variables declaration//GEN-END:variables
}
